import { StyleSheet, Dimensions, Platform } from 'react-native';
const { height, width } = Dimensions.get('window');
const HEADER_MIN_HEIGHT = 220;
export const styles = StyleSheet.create({
    mainWrapper: { flex: 1, backgroundColor: '#0A0A12' },
    headerContainer: { position: 'absolute', top: 0, left: 0, right: 0, width: width, zIndex: 10, overflow: 'hidden' },
    headerImage: { width: '100%', height: '100%' },
    darkOverlayImage: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(10, 10, 18, 0.45)' },
    headerOverlayContent: { ...StyleSheet.absoluteFillObject, justifyContent: 'space-between', alignItems: 'center', paddingVertical: 100 },
    scrollContent: { flexGrow: 1 },
    formContainer: { minHeight: height - HEADER_MIN_HEIGHT, width: width, backgroundColor: '#0A0A12', alignItems: 'center', paddingTop: 30, paddingBottom: 60 },
    logoTextStart: { color: '#fff', fontSize: 42, fontWeight: 'bold', letterSpacing: 2, textShadowColor: '#FF1493', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 20 },
    swipeIndicator: { alignItems: 'center' },
    swipeText: { color: 'rgba(255,255,255,0.85)', fontSize: 16, marginBottom: 5 },
    arrow: { color: '#fff', fontSize: 35, fontWeight: 'bold', textShadowColor: '#FF1493', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 20 },
    keyboardView: { width: '100%', alignItems: 'center' },
    glassCard: { width: '92%', backgroundColor: 'rgba(255, 255, 255, 0.04)', borderRadius: 20, paddingHorizontal: 20, paddingVertical: 30, borderWidth: 1, borderColor: 'rgba(255, 20, 147, 0.15)' },
    loginTitle: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 25, alignSelf: 'flex-start' },
    form: { width: '100%' },
    input: { backgroundColor: 'transparent', padding: 16, borderRadius: 10, marginBottom: 16, color: '#fff', borderWidth: 1, borderColor: 'rgba(255, 20, 147, 0.25)', fontSize: 15 },
    passwordInputContainer: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255, 20, 147, 0.25)', borderRadius: 10, marginBottom: 16, paddingRight: 14 },
    passwordInputField: { flex: 1, backgroundColor: 'transparent', padding: 16, color: '#fff', fontSize: 15 },
    eyeButton: { padding: 4, justifyContent: 'center', alignItems: 'center' },
    inputError: { borderColor: '#FF1493' },
    errorText: { color: '#FF1493', fontSize: 12, marginTop: -10, marginBottom: 15, marginLeft: 5 },
    forgotPasswordContainer: { alignSelf: 'flex-end', marginTop: -4, marginBottom: 24 },
    forgotPasswordText: { color: 'rgba(255, 182, 193, 0.6)', fontSize: 13 },
    mainButton: { backgroundColor: '#FF1493', padding: 16, borderRadius: 10, alignItems: 'center' },
    buttonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
    dividerContainer: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
    line: { flex: 1, height: 1, backgroundColor: 'rgba(255, 20, 147, 0.15)' },
    orText: { color: '#FF1493', marginHorizontal: 10, fontSize: 14 },
    toggleLink: { alignItems: 'center', marginTop: 5 },
    toggleText: { color: '#FF1493', fontSize: 14, fontWeight: '500' },

    dashboardWrapper: { flex: 1, backgroundColor: '#0A0A12', paddingTop: Platform.OS === 'ios' ? 50 : 20 },
    internalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, marginBottom: 15 },
    internalLogo: { color: '#fff', fontSize: 28, fontWeight: 'bold', letterSpacing: 1.5, textShadowColor: '#FF1493', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 10 },
    logoutBtn: { backgroundColor: 'rgba(255,20,147,0.12)', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8, borderWidth: 1, borderColor: 'rgba(255,20,147,0.3)' },
    logoutBtnText: { color: '#FF1493', fontSize: 13, fontWeight: '600' },
    bottomTabBar: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 85, backgroundColor: '#121222', borderTopWidth: 1, borderColor: 'rgba(255,20,147,0.15)', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingBottom: 15, zIndex: 99 },
    tabItem: { alignItems: 'center', justifyContent: 'center', flex: 1, height: '100%', opacity: 0.5 },
    tabItemActive: { opacity: 1 },
    tabIcon: { fontSize: 22, marginBottom: 3 },
    tabLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 11, fontWeight: '600' },
    tabLabelActive: { color: '#FF1493' },
    searchContainer: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 12, marginHorizontal: 16, paddingHorizontal: 12, alignItems: 'center', height: 48, marginBottom: 15, borderWidth: 1, borderColor: '#FF1493' },
    searchBarInput: { flex: 1, color: '#000', fontSize: 16, paddingVertical: 0 },
    searchIconSymbol: { fontSize: 18, color: '#FF1493' },
    categoryPill: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: 'rgba(255,20,147,0.04)', marginRight: 10, borderWidth: 1, borderColor: 'rgba(255,20,147,0.2)' },
    categoryPillActive: { backgroundColor: '#FF1493', borderColor: '#FF1493' },
    categoryText: { color: 'rgba(255,182,193,0.7)', fontWeight: '600', fontSize: 14 },
    categoryTextActive: { color: '#fff' },
    sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#fff', marginBottom: 15 },
    emptyText: { color: 'rgba(255,182,193,0.4)', textAlign: 'center', marginTop: 20 },

    workoutCard: { width: '100%', height: 190, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255,20,147,0.15)' },
    cardImageBackground: { width: '100%', height: '100%' },
    cardDarkOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(10, 10, 18, 0.6)' },
    cardContentContainer: { flex: 1, justifyContent: 'space-between', padding: 18 },
    cardSportTitle: { color: '#fff', fontSize: 22, fontWeight: 'bold' },
    cardSubDetails: { color: 'rgba(255,255,255,0.75)', fontSize: 13, marginTop: 2 },
    cardTimeText: { color: '#00E5FF', fontSize: 12, marginTop: 4 },
    cardBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
    slotsText: { color: '#fff', fontSize: 12, fontWeight: 'bold' },
    bookButton: { backgroundColor: '#FF1493', paddingVertical: 8, paddingHorizontal: 18, borderRadius: 20 },
    bookButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },

    profileMainContainer: { flex: 1, backgroundColor: '#0A0A12' },
    profileDarkOverlayGraduation: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(10, 10, 18, 0.45)' },
    profileGlassFloatCard: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(16, 16, 28, 0.92)',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: Platform.OS === 'ios' ? 95 : 100,
        borderTopWidth: 1,
        borderColor: 'rgba(255, 20, 147, 0.28)'
    },
    profileGlassHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    profileGlassName: { color: '#fff', fontSize: 24, fontWeight: 'bold' },
    profileGlassSubTag: { color: '#00E5FF', fontSize: 12, fontWeight: '600', marginTop: 1 },
    profileUploadRealButton: { backgroundColor: '#FF1493', width: 42, height: 42, borderRadius: 21, justifyContent: 'center', alignItems: 'center' },
    profileGlassBioText: { color: 'rgba(255,255,255,0.65)', fontSize: 13, lineHeight: 18, marginBottom: 15 },
    profileStatsRowTable: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: 16, paddingVertical: 12, paddingHorizontal: 10, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)' },
    profileStatsItemBox: { flex: 1, alignItems: 'center' },
    profileStatNumber: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
    profileStatLabel: { color: 'rgba(255,182,193,0.6)', fontSize: 11, marginTop: 2 },
    profileSectionInnerTitle: { color: '#FF1493', fontSize: 13, fontWeight: 'bold', marginBottom: 10, letterSpacing: 0.5 },
    profileNoClassesText: { color: 'rgba(255,255,255,0.4)', fontSize: 11, fontStyle: 'italic', marginVertical: 6 },
    profileClassListRowStrip: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.02)', padding: 10, borderRadius: 8, marginBottom: 6 },
    profileStripSportName: { color: '#fff', fontSize: 13, fontWeight: '500' },
    profileStripTime: { color: '#00E5FF', fontSize: 12, fontWeight: '600' },
    profileInlineLogoutMinimalButton: { alignSelf: 'center', marginTop: 12, opacity: 0.35 },
    profileInlineLogoutMinimalText: { color: '#fff', fontSize: 11 },

    buySubShopCardItem: { width: 150, backgroundColor: 'rgba(255,255,255,0.04)', padding: 12, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,20,147,0.2)', alignItems: 'center' },
    shopSubTitleName: { color: '#fff', fontSize: 11, fontWeight: 'bold', textAlign: 'center' },
    shopSubPriceText: { color: '#00E5FF', fontSize: 14, fontWeight: 'bold', marginVertical: 4 },
    shopSubDescText: { color: 'rgba(255,255,255,0.5)', fontSize: 10, textAlign: 'center' },

    labelField: { color: '#fff', fontSize: 13, marginBottom: 6, fontWeight: '600' },
    staffFormCard: { backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: 16, padding: 20, borderWidth: 1, borderColor: 'rgba(255,20,147,0.2)', marginTop: 10 },
    staffCardTitle: { color: '#FF1493', fontSize: 18, fontWeight: 'bold', marginBottom: 2 },
    staffCardSubtitle: { color: 'rgba(255,182,193,0.5)', fontSize: 12, marginBottom: 15 },
    staffInput: { borderWidth: 1, borderColor: 'rgba(255,20,147,0.25)', borderRadius: 10, padding: 12, color: '#fff', marginBottom: 15, fontSize: 14, backgroundColor: 'rgba(255,255,255,0.01)' },
    roomPill: { backgroundColor: 'rgba(255,255,255,0.05)', paddingVertical: 10, paddingHorizontal: 16, marginRight: 8, borderRadius: 10, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,20,147,0.2)' },
    roomPillActive: { backgroundColor: '#FF1493', borderColor: '#FF1493' },
    staffButton: { backgroundColor: '#FF1493', padding: 14, borderRadius: 10, alignItems: 'center', marginTop: 5 },
    staffButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 15 },
    trainerRosterCard: { backgroundColor: 'rgba(255, 20, 147, 0.05)', borderRadius: 12, padding: 12, marginTop: 6, borderWidth: 1, borderColor: 'rgba(255, 20, 147, 0.2)' },
    rosterTitle: { color: '#FF1493', fontSize: 13, fontWeight: 'bold', marginBottom: 6 },
    rosterEmptyText: { color: 'rgba(255, 20, 147, 0.4)', fontSize: 12, fontStyle: 'italic', paddingLeft: 6 },
    rosterMemberName: { color: '#fff', fontSize: 13, paddingVertical: 2, paddingLeft: 6, fontWeight: '500' },
});